# Copy init-couchbase files into image.

RUN mkdir -p /init-couchbase
COPY init-couchbase /init-couchbase
RUN chmod +x /init-couchbase/*.sh

# Copy play-server's run-*.sh files into image.

COPY cmd/play-server/run-*.sh /
RUN chmod +x /run-*.sh

# Create user for user-submitted playground code.

RUN useradd play -u 1001 -g couchbase -M
