ARG CB_EDITION=enterprise
ARG CB_VERSION=7.0.0-beta
ARG CB_IMAGE=couchbase:$CB_EDITION-$CB_VERSION

ARG BASE_IMAGE=ubuntu:20.04

# SDK related images...

FROM adoptopenjdk AS adoptopenjdk

FROM maven AS maven

FROM golang AS golang

FROM node:14 AS node

FROM mcr.microsoft.com/dotnet/core/sdk AS dotnet_core_sdk
