ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && \
    apt-get install -y \
	git curl wget jq unzip zip \
	build-essential cmake libssl-dev \
	atop htop psmisc strace time \
	emacs vim

# ------------------------------------------------------

RUN apt-get install -y python3-dev python3-pip python3-setuptools

RUN python3 --version && \
    pip3 --version

COPY --from=golang /usr/local/go /usr/local/go
COPY --from=golang /go /go

ENV GOPATH /go
ENV PATH="$PATH:/usr/local/go/bin:$GOPATH/bin"

RUN go version

COPY --from=adoptopenjdk /opt/java /opt/java

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="$PATH:/opt/java/openjdk/bin"

RUN javac --version && \
    java --version

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/include/node /usr/local/include/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN ln -s ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && \
    node --version && \
    npm --version

COPY --from=dotnet_core_sdk /usr/share/dotnet /usr/share/dotnet
COPY --from=dotnet_core_sdk /usr/share/powershell /usr/share/powershell

RUN ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet && \
    ln -s /usr/share/powershell/pwsh /usr/bin/pwsh && \
    dotnet --version && \
    pwsh -Version

# ------------------------------------------------------

# Install python couchbase SDK, see:
# https://docs.couchbase.com/tutorials/quick-start/quickstart-python3-native-firstquery-cb65.html

RUN pip3 install six couchbase
RUN pip3 show couchbase | grep Version | cut -f 2 -d ' ' > /opt/couchbase/VERSION-sdk-python.ver

# ------------------------------------------------------

# Install golang couchbase SDK:

RUN go get github.com/couchbase/gocb


# -------------------------------------------------------
#   PHP
# -------------------------------------------------------
RUN apt-get update && \
    apt -y install software-properties-common apt-transport-https vim && \
    LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php   
RUN apt-get update && \
    apt-get -y install php${PHP_VERSION} php${PHP_VERSION}-cli php${PHP_VERSION}-common php${PHP_VERSION}-fpm php${PHP_VERSION}-dev php${PHP_VERSION}-xml 
RUN php -v

# Get the Couchbase Repository Key
ADD https://packages.couchbase.com/clients/c/repos/deb/couchbase.key .

RUN apt-get update \
    && apt-get install -y lsb-release software-properties-common gnupg2 \
    && apt-key add ./couchbase.key \
    && rm ./couchbase.key \
    && apt-add-repository "deb http://packages.couchbase.com/clients/c/repos/deb/${CB_CLIENT_OS} ${CB_CLIENT_OS_TYPE} ${CB_CLIENT_OS_TYPE}/main" \
    && apt-get update \
    && apt-get install -y --allow-unauthenticated libcouchbase3 libcouchbase-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent

# Install ext-couchbase
RUN pecl install https://packages.couchbase.com/clients/php/couchbase-${COUCHBASE_SDK_PHP_VERSION}.tgz && \
    cp /usr/lib/php/${PHP_VERSION}/php.ini-development /usr/lib/php/${PHP_VERSION}/php.ini && \
    printf 'extension=json.so\nextension=couchbase.so' >> /etc/php/${PHP_VERSION}/cli/php.ini

