ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG BASE_IMAGE

ARG CB_CLIENT_OS
ARG CB_CLIENT_OS_TYPE

ARG PHP_VERSION
ARG COUCHBASE_SDK_PHP_VERSION

ARG SCALA_VERSION
ARG SBT_VERSION
ARG COUCHBASE_SDK_SCALA_VERSION

# Create couchbase user with UID 1000, which is necessary to match
# the default boot2docker UID.
RUN groupadd -g 1000 couchbase && useradd couchbase -u 1000 -g couchbase -M

RUN mkdir -p /opt/couchbase/var

VOLUME /opt/couchbase/var
