#!/usr/bin/env python3

# Move to the previous tutorial step.

import os

dirPath, fileName = os.path.split(os.path.abspath(__file__))

try:
    with open(dirPath + "/CURRENT") as f:
        name, step = f.read().split(':')

    try:
        step = str(int(step) - 1)

        with open(dirPath + "/tutorial-" + name + "/step-" + step.zfill(3)) as f:
            pass # The step exists.

    except:
        step = '0'

    with open(dirPath + "/CURRENT", 'w') as c:
        c.write(name + ":" + step)

except:
    pass

os.system(dirPath + "/show")
