#!/usr/bin/env python3

# Start a tutorial.

import os
import sys

dirPath, fileName = os.path.split(os.path.abspath(__file__))

try:
    name = 'default'
    if len(sys.argv) > 1:
        name = sys.argv[1]

    step = '0'
    if len(sys.argv) > 2:
        step = sys.argv[2]

    with open(dirPath + "/tutorial-" + name + "/step-" + step.zfill(3)) as f:
        with open(dirPath + "/CURRENT", 'w') as c:
            c.write(name + ":" + step)

        os.system(dirPath + "/show")

except:
    print("ERROR: Could not start that tutorial or step.")
