@startuml Playground_cbauth
title <font style="underscore">Playground encrypted password support
skinparam Style strict
actor Developer
participant Http
participant ET

Developer -> Http ++ : 1. /et?ct=password \nto get ET (Encrypted Text)
Http -> ET ++ : encrypt(internal key,cleartext)
note left
 Encrypt with internal key + base64 encode to get the encrypted text 
 of cbpwd or other cbuser/cburl
 Examples: https://play.golang.org/p/4FQBAeHgRs
 https://www.melvinvivas.com/how-to-encrypt-and-decrypt-data-using-aes
end note
return ET string
Developer <-- Http  --: return ET string


Developer -> Http ++ : 2. /run code having ET surround with %%%,\n like %%%<encryptedtext>%%% \n(in the github code to run now)
Http -> ET ++: decrypt(internal key, encryptedtext)
note left
    Search for any %%%(.%)%%% in the code.
    Decrypt with base64 decode + decrypt with internal key 
    to get back clear text. 
    Replace the code internally before execution.
end note
return clear text string
return result


@enduml