@startuml PlaygrounAuth
skinparam Style strict
actor Developer
participant Http
participant HttpProxy
participant AuthProxy

Developer -> Http : get ET (Encrypted Text) for cburl,cbuser,cbpwd
Http -> AuthProxy ++ : get ET string
AuthProxy -> AuthProxy : create ET using internal secret salt
Http <-- AuthProxy : return ET string
AuthProxy --
Developer <-- Http : return ET string

Developer -> Http : /run code having ET (github code run now)
Http -> AuthProxy : get url, user, pwd
return ok


@enduml