@startuml CouchbaseDevContainerCapella
title \nUse Case#4. Couchbase Dev container - Capella\n
skinparam Style strict
skinparam lifelineStrategy solid

actor Developer
rectangle Client {
    usecase (couchbase-dev-container \n gitrepo) as UC1
usecase UC2 as "VS Code
Remote containers 
--
Couchbase SDKs
Playground Examples 
--
on developer machine"
}
rectangle "Data Layer" {
    usecase (\n\nCouchbase Cluster \n on Capella\n\n) as UC3
}
Developer -> UC1
UC1 -> UC2

UC2 -> UC3 : data

@enduml