name: Playground health checks

on:
  push:
    - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  health-check-run-with-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Google Chrome
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt -qq install ./google-chrome-stable_current_amd64.deb
        google-chrome-stable --version
    - name: Run selenium tests
      run: |
        cd tests
        pip install -r requirements.txt
        DRIVER_OPTIONS='-headless' CBLIVE_URL='https://couchbase.live' python cblive_playground_browsertest.py  2>&1 | tee -a ./tests_run_log.txt
        env
        chmod a+x ../.github/workflows/send_pg_health.sh
        ../.github/workflows/send_pg_health.sh ./tests_run_log.txt ${GITHUB_RUN_ID} ${{ secrets.SLACK_WEBHOOK_URL_TEST }} ${{ secrets.API_TOKEN_TO_GITHUB }}
        
